{% set name = "puremagic" %}
{% set version = "1.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cdgriffith/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f1e3e1d5b2d3fd58f98ba05775b21b134ce105d423543a497bedaebdbc1309c6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - test
  imports:
    - puremagic
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv .

about:
  home: https://github.com/cdgriffith/puremagic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python implementation of magic file detection
  description: |
    puremagic is a pure python module that will identify a file based off it's magic numbers.
  doc_url: https://github.com/cdgriffith/puremagic
  dev_url: https://github.com/cdgriffith/puremagic

extra:
  recipe-maintainers:
    - andreyz4k
