{% set name = "puremagic" %}
{% set version = "1.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 195893fc129657f611b86b959aab337207d6df7f25372209269ed9e303c1a8c0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - test
  imports:
    - puremagic
  commands:
    - pip check
    - pytest -v test
  requires:
    - pip
    - python
    - pytest

about:
  home: https://github.com/cdgriffith/puremagic
  summary: Pure python implementation of magic file detection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Pure python implementation of identifying files based off their magic numbers
  dev_url: https://github.com/cdgriffith/puremagic
  doc_url: https://github.com/cdgriffith/puremagic/blob/master/README.rst

extra:
  recipe-maintainers:
    - andreyz4k
