travis:
  secure:
    BINSTAR_TOKEN: HTFdd+wuY7gvla+OQZSZAF5Q5XNeSJNw+7uXPm+K467daEeTyxi6/xkJAsfjfAELa8lw7FO5HivUx8CJEeisx5pQadYRa0z+/7l/XOW59PhdsGSSAZhIDAvHoFYETOARi+q9vMbwR0hAZAmTlnvswRj7eqaQmSeQDzOro4Vr0C3jRPigmivJhcw9LEhqgVEtKr0R0f3S/+qVFhQdLlTConNbbr3hqw453on0rjqHu2P28mwL6YHZNZ153VIi+khAiZZzm8BAJoNUxNUNLNzb1uLW685FGN7tN4rI0g22Rk6WgOpKsp9My5U5BYdpCTZ8E1ckDxh4GlXkoFAGgyuxVt2i5Cyb/+dCWzr2C9mKJoQDA6ngS4OToebVEhgGZYclhqk6TxpekqXPRmpCdk8TcYEfl9ToIgLiR+dXPSVAI11aWBaIf/nBO/YbMspYZTWCnOGRF6dT4mRiAZs1DerHbPMdNt51hyA2iLVMh0kxs49RKD1sv5qBhoCqXRDSeFWpjr4mei0bsh503YIkkmME7hQI8tEtHVTS6YLj6VJYJUCdGREXOw8bLZKtg47FgLpN0XLWf+R3T96CQ0PCMeGPoKJTms8NuILLNpNb+QubC8DB5QP55SASaR1O93vOi82yilabVnQXh/D4uCfjCu2kkY5k9r7d4Ig3GxXL56ZuHeI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
